# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'VDD_Network_Layers_Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestNetworkLayers
  pod 'Alamofire', '~> 4.7'
  pod 'HydraAsync'
  pod 'SwiftyJSON'

end
