# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

def shared_pods
  pod 'Alamofire', '~> 4.7'
  pod 'HydraAsync'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
end

target 'AppStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for AppStore
  shared_pods
end

target 'Develop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Develop
  shared_pods
end

target 'Staging' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Staging
  shared_pods
end
